# Generated by Django 5.2.17 on 2026-08-20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_issue_revision_issuecomment_revision_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("planned", "Planned"),
                    ("in_progress", "In progress"),
                    ("done", "Done"),
                    ("closed", "Closed"),
                    ("declined", "Declined"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issueevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("comment_added", "Comment added"),
                    ("comment_updated", "Comment updated"),
                    ("upvote_added", "Upvote added"),
                    ("upvote_removed", "Upvote removed"),
                    ("duplicate_linked", "Duplicate linked"),
                    ("duplicate_unlinked", "Duplicate unlinked"),
                    ("delivery_linked", "Delivery linked"),
                    ("delivery_unlinked", "Delivery unlinked"),
                    ("scope_assessed", "Scope assessed"),
                    ("auto_declined", "Automatically declined"),
                    ("spec_updated", "Project spec updated"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ProjectSpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("auto_decline_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="spec", to="projects.project")),
            ],
        ),
        migrations.CreateModel(
            name="IssueScopeAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("spec_revision", models.PositiveBigIntegerField()),
                ("state", models.CharField(choices=[("completed", "Completed"), ("failed", "Failed")], db_index=True, default="completed", max_length=16)),
                ("verdict", models.CharField(blank=True, choices=[("in_scope", "In scope"), ("out_of_scope", "Out of scope"), ("spec_gap", "Spec gap"), ("needs_review", "Needs review")], db_index=True, max_length=24)),
                ("public_reason", models.CharField(blank=True, max_length=500)),
                ("out_of_scope_quote", models.CharField(blank=True, max_length=1000)),
                ("spec_gap_summary", models.CharField(blank=True, max_length=1000)),
                ("evaluator_version", models.CharField(default="spec_scope_v1", max_length=64)),
                ("auto_declined", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scope_assessments", to="projects.issue")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="ProjectSpecChangeProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_spec_revision", models.PositiveBigIntegerField()),
                ("base_content", models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ("proposed_content", models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ("summary", models.CharField(max_length=1000)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")], db_index=True, default="pending", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="created_spec_change_proposals", to=settings.AUTH_USER_MODEL)),
                ("issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="spec_change_proposals", to="projects.issue")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="spec_change_proposals", to="projects.project")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_spec_change_proposals", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="issuescopeassessment",
            index=models.Index(fields=["issue", "-created_at"], name="scope_assess_issue_at_idx"),
        ),
    ]
