# Generated by Django 5.2.11 on 2026-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_api_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="can_write",
            field=models.BooleanField(default=True),
        ),
    ]
