# Generated by Django 5.2.11 on 2026-02-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_api_token_can_write'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='is_agent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
